import React, { useEffect, useState } from 'react';
import { SEOHead } from '../components/SEOHead';
import { getConstructionNews } from '../services/geminiService';
import { NewsItem, LoadingState } from '../types';
import { ExternalLink, RefreshCw, AlertCircle } from 'lucide-react';

export const News: React.FC = () => {
  const [news, setNews] = useState<string>("");
  const [sources, setSources] = useState<NewsItem[]>([]);
  const [status, setStatus] = useState<LoadingState>(LoadingState.IDLE);

  const fetchNews = async () => {
    setStatus(LoadingState.LOADING);
    const data = await getConstructionNews();
    if (data.text) {
      setNews(data.text);
      setSources(data.links);
      setStatus(LoadingState.SUCCESS);
    } else {
      setStatus(LoadingState.ERROR);
    }
  };

  useEffect(() => {
    fetchNews();
  }, []);

  return (
    <>
      <SEOHead 
        title="Industry News" 
        description="Latest news and trends in the Nigerian construction and granite industry." 
      />
      
      <div className="bg-surface min-h-screen py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center mb-8">
            <h1 className="text-3xl font-heading font-bold text-primary">Industry Updates</h1>
            <button 
              onClick={fetchNews} 
              className="flex items-center text-sm text-primary hover:text-accent transition"
            >
              <RefreshCw size={16} className={`mr-2 ${status === LoadingState.LOADING ? 'animate-spin' : ''}`} />
              Refresh
            </button>
          </div>

          <div className="bg-white p-8 rounded-lg shadow-md border-t-4 border-accent">
            {status === LoadingState.LOADING && (
              <div className="flex flex-col items-center justify-center py-12">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mb-4"></div>
                <p className="text-gray-500">Searching the web for latest construction trends...</p>
              </div>
            )}

            {status === LoadingState.ERROR && (
              <div className="flex items-center text-red-500">
                <AlertCircle className="mr-2" />
                <p>Unable to retrieve news at this moment. Please try again later.</p>
              </div>
            )}

            {status === LoadingState.SUCCESS && (
              <div className="prose prose-blue max-w-none">
                <h3 className="text-xl font-bold text-gray-900 mb-4">Market Summary</h3>
                <div className="text-gray-700 whitespace-pre-line leading-relaxed mb-8">
                  {news}
                </div>

                {sources.length > 0 && (
                  <div className="bg-gray-50 p-4 rounded-lg">
                    <h4 className="text-sm font-bold text-gray-500 uppercase mb-3">Sources & Further Reading</h4>
                    <ul className="space-y-2">
                      {sources.map((source, idx) => (
                        <li key={idx}>
                          <a 
                            href={source.url} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="flex items-center text-primary hover:text-accent transition text-sm font-medium"
                          >
                            <ExternalLink size={14} className="mr-2" />
                            {source.title}
                          </a>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                
                <p className="text-xs text-gray-400 mt-6 text-right">
                  Generated by Gemini AI using Google Search Grounding.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
};